-- 맴버 테이블 생성
CREATE TABLE IF NOT EXISTS TB_MEMBER
(
    MEMBER_SEQ BIGINT PRIMARY KEY,
    MEMBER_ID VARCHAR(255) NOT NULL,
    MEMBER_NAME VARCHAR(255) NOT NULL,
    MEMBER_PWD VARCHAR(255) NOT NULL
    );


-- 보드 테이블 생성
CREATE TABLE IF NOT EXISTS TB_BOARD
(
    BOARD_SEQ  INT  PRIMARY KEY NOT NULL,
    BOARD_TITLE VARCHAR(100) NOT NULL,
    BOARD_CONTENT TEXT NOT NULL,
    created_DATE TIMESTAMP NOT NULL,
    board_Views INT DEFAULT 0,
    category VARCHAR(50) NOT NULL,
    MEMBER_SEQ BIGINT, -- 맴버 테이블의 시퀀스를 참조하는 외래 키
    CONSTRAINT fk_MEMBER_SEQ FOREIGN KEY (MEMBER_SEQ) REFERENCES TB_MEMBER (MEMBER_SEQ)
    );

-- 시퀀스
CREATE SEQUENCE IF NOT EXISTS MEMBER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS BOARD_SEQ START WITH 1 INCREMENT BY 1;


