-- 맴버 테이블 생성
CREATE TABLE IF NOT EXISTS TB_MEMBER
(
    MEMBER_SEQ BIGINT PRIMARY KEY,
    MEMBER_ID VARCHAR(255) NOT NULL,
    MEMBER_NAME VARCHAR(255) NOT NULL,
    MEMBER_PWD VARCHAR(255) NOT NULL
    );

-- 시퀀스
CREATE SEQUENCE IF NOT EXISTS MEMBER_SEQ START WITH 1 INCREMENT BY 1;


